services:
  - type: web
    name: pharma-admin
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x scripts/render_build.sh && ./scripts/render_build.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 